/*
Vaudience AI Core API

API for the Vaudience AI Core

API version: 0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
)

// checks if the AgentQuickFilterI18n type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentQuickFilterI18n{}

// AgentQuickFilterI18n struct for AgentQuickFilterI18n
type AgentQuickFilterI18n struct {
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AgentQuickFilterI18n AgentQuickFilterI18n

// NewAgentQuickFilterI18n instantiates a new AgentQuickFilterI18n object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentQuickFilterI18n() *AgentQuickFilterI18n {
	this := AgentQuickFilterI18n{}
	return &this
}

// NewAgentQuickFilterI18nWithDefaults instantiates a new AgentQuickFilterI18n object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentQuickFilterI18nWithDefaults() *AgentQuickFilterI18n {
	this := AgentQuickFilterI18n{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AgentQuickFilterI18n) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentQuickFilterI18n) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AgentQuickFilterI18n) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AgentQuickFilterI18n) SetName(v string) {
	o.Name = &v
}

func (o AgentQuickFilterI18n) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentQuickFilterI18n) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AgentQuickFilterI18n) UnmarshalJSON(data []byte) (err error) {
	varAgentQuickFilterI18n := _AgentQuickFilterI18n{}

	err = json.Unmarshal(data, &varAgentQuickFilterI18n)

	if err != nil {
		return err
	}

	*o = AgentQuickFilterI18n(varAgentQuickFilterI18n)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAgentQuickFilterI18n struct {
	value *AgentQuickFilterI18n
	isSet bool
}

func (v NullableAgentQuickFilterI18n) Get() *AgentQuickFilterI18n {
	return v.value
}

func (v *NullableAgentQuickFilterI18n) Set(val *AgentQuickFilterI18n) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentQuickFilterI18n) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentQuickFilterI18n) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentQuickFilterI18n(val *AgentQuickFilterI18n) *NullableAgentQuickFilterI18n {
	return &NullableAgentQuickFilterI18n{value: val, isSet: true}
}

func (v NullableAgentQuickFilterI18n) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentQuickFilterI18n) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


