/*
Vaudience AI Core API

API for the Vaudience AI Core

API version: 0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// checks if the CredentialsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialsResponse{}

// CredentialsResponse struct for CredentialsResponse
type CredentialsResponse struct {
	OtpAllowed bool `json:"otp_allowed"`
	OtpEnabled bool `json:"otp_enabled"`
	AdditionalProperties map[string]interface{}
}

type _CredentialsResponse CredentialsResponse

// NewCredentialsResponse instantiates a new CredentialsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialsResponse(otpAllowed bool, otpEnabled bool) *CredentialsResponse {
	this := CredentialsResponse{}
	this.OtpAllowed = otpAllowed
	this.OtpEnabled = otpEnabled
	return &this
}

// NewCredentialsResponseWithDefaults instantiates a new CredentialsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialsResponseWithDefaults() *CredentialsResponse {
	this := CredentialsResponse{}
	return &this
}

// GetOtpAllowed returns the OtpAllowed field value
func (o *CredentialsResponse) GetOtpAllowed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OtpAllowed
}

// GetOtpAllowedOk returns a tuple with the OtpAllowed field value
// and a boolean to check if the value has been set.
func (o *CredentialsResponse) GetOtpAllowedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtpAllowed, true
}

// SetOtpAllowed sets field value
func (o *CredentialsResponse) SetOtpAllowed(v bool) {
	o.OtpAllowed = v
}

// GetOtpEnabled returns the OtpEnabled field value
func (o *CredentialsResponse) GetOtpEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OtpEnabled
}

// GetOtpEnabledOk returns a tuple with the OtpEnabled field value
// and a boolean to check if the value has been set.
func (o *CredentialsResponse) GetOtpEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtpEnabled, true
}

// SetOtpEnabled sets field value
func (o *CredentialsResponse) SetOtpEnabled(v bool) {
	o.OtpEnabled = v
}

func (o CredentialsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["otp_allowed"] = o.OtpAllowed
	toSerialize["otp_enabled"] = o.OtpEnabled

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CredentialsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"otp_allowed",
		"otp_enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCredentialsResponse := _CredentialsResponse{}

	err = json.Unmarshal(data, &varCredentialsResponse)

	if err != nil {
		return err
	}

	*o = CredentialsResponse(varCredentialsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "otp_allowed")
		delete(additionalProperties, "otp_enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCredentialsResponse struct {
	value *CredentialsResponse
	isSet bool
}

func (v NullableCredentialsResponse) Get() *CredentialsResponse {
	return v.value
}

func (v *NullableCredentialsResponse) Set(val *CredentialsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialsResponse(val *CredentialsResponse) *NullableCredentialsResponse {
	return &NullableCredentialsResponse{value: val, isSet: true}
}

func (v NullableCredentialsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


