/*
vAudience AIgentChat API

chat and api server for AIgents

API version: 0.15.9
Contact: contact@vaudience.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aigentchat

import (
	"encoding/json"
)

// checks if the AIgencyMessageFileList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AIgencyMessageFileList{}

// AIgencyMessageFileList struct for AIgencyMessageFileList
type AIgencyMessageFileList struct {
	Files []AIgencyMessageFile `json:"files,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AIgencyMessageFileList AIgencyMessageFileList

// NewAIgencyMessageFileList instantiates a new AIgencyMessageFileList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAIgencyMessageFileList() *AIgencyMessageFileList {
	this := AIgencyMessageFileList{}
	return &this
}

// NewAIgencyMessageFileListWithDefaults instantiates a new AIgencyMessageFileList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAIgencyMessageFileListWithDefaults() *AIgencyMessageFileList {
	this := AIgencyMessageFileList{}
	return &this
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *AIgencyMessageFileList) GetFiles() []AIgencyMessageFile {
	if o == nil || IsNil(o.Files) {
		var ret []AIgencyMessageFile
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AIgencyMessageFileList) GetFilesOk() ([]AIgencyMessageFile, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *AIgencyMessageFileList) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []AIgencyMessageFile and assigns it to the Files field.
func (o *AIgencyMessageFileList) SetFiles(v []AIgencyMessageFile) {
	o.Files = v
}

func (o AIgencyMessageFileList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AIgencyMessageFileList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AIgencyMessageFileList) UnmarshalJSON(data []byte) (err error) {
	varAIgencyMessageFileList := _AIgencyMessageFileList{}

	err = json.Unmarshal(data, &varAIgencyMessageFileList)

	if err != nil {
		return err
	}

	*o = AIgencyMessageFileList(varAIgencyMessageFileList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "files")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAIgencyMessageFileList struct {
	value *AIgencyMessageFileList
	isSet bool
}

func (v NullableAIgencyMessageFileList) Get() *AIgencyMessageFileList {
	return v.value
}

func (v *NullableAIgencyMessageFileList) Set(val *AIgencyMessageFileList) {
	v.value = val
	v.isSet = true
}

func (v NullableAIgencyMessageFileList) IsSet() bool {
	return v.isSet
}

func (v *NullableAIgencyMessageFileList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAIgencyMessageFileList(val *AIgencyMessageFileList) *NullableAIgencyMessageFileList {
	return &NullableAIgencyMessageFileList{value: val, isSet: true}
}

func (v NullableAIgencyMessageFileList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAIgencyMessageFileList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


