/*
vAudience AIgentChat API

chat and api server for AIgents

API version: 0.20.10
Contact: contact@vaudience.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aigentchat

import (
	"encoding/json"
)

// checks if the FunctionCallI18n type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionCallI18n{}

// FunctionCallI18n struct for FunctionCallI18n
type FunctionCallI18n struct {
	Description *string `json:"description,omitempty"`
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FunctionCallI18n FunctionCallI18n

// NewFunctionCallI18n instantiates a new FunctionCallI18n object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionCallI18n() *FunctionCallI18n {
	this := FunctionCallI18n{}
	return &this
}

// NewFunctionCallI18nWithDefaults instantiates a new FunctionCallI18n object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionCallI18nWithDefaults() *FunctionCallI18n {
	this := FunctionCallI18n{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *FunctionCallI18n) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionCallI18n) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *FunctionCallI18n) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *FunctionCallI18n) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FunctionCallI18n) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionCallI18n) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FunctionCallI18n) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FunctionCallI18n) SetName(v string) {
	o.Name = &v
}

func (o FunctionCallI18n) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionCallI18n) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FunctionCallI18n) UnmarshalJSON(data []byte) (err error) {
	varFunctionCallI18n := _FunctionCallI18n{}

	err = json.Unmarshal(data, &varFunctionCallI18n)

	if err != nil {
		return err
	}

	*o = FunctionCallI18n(varFunctionCallI18n)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFunctionCallI18n struct {
	value *FunctionCallI18n
	isSet bool
}

func (v NullableFunctionCallI18n) Get() *FunctionCallI18n {
	return v.value
}

func (v *NullableFunctionCallI18n) Set(val *FunctionCallI18n) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionCallI18n) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionCallI18n) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionCallI18n(val *FunctionCallI18n) *NullableFunctionCallI18n {
	return &NullableFunctionCallI18n{value: val, isSet: true}
}

func (v NullableFunctionCallI18n) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionCallI18n) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


