/*
vAudience AIgentChat API

chat and api server for AIgents

API version: 0.25.2
Contact: contact@vaudience.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aigentchat

import (
	"encoding/json"
)

// checks if the AIModelStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AIModelStats{}

// AIModelStats struct for AIModelStats
type AIModelStats struct {
	Cost *int32 `json:"cost,omitempty"`
	Intelligence *int32 `json:"intelligence,omitempty"`
	Speed *int32 `json:"speed,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AIModelStats AIModelStats

// NewAIModelStats instantiates a new AIModelStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAIModelStats() *AIModelStats {
	this := AIModelStats{}
	return &this
}

// NewAIModelStatsWithDefaults instantiates a new AIModelStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAIModelStatsWithDefaults() *AIModelStats {
	this := AIModelStats{}
	return &this
}

// GetCost returns the Cost field value if set, zero value otherwise.
func (o *AIModelStats) GetCost() int32 {
	if o == nil || IsNil(o.Cost) {
		var ret int32
		return ret
	}
	return *o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AIModelStats) GetCostOk() (*int32, bool) {
	if o == nil || IsNil(o.Cost) {
		return nil, false
	}
	return o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *AIModelStats) HasCost() bool {
	if o != nil && !IsNil(o.Cost) {
		return true
	}

	return false
}

// SetCost gets a reference to the given int32 and assigns it to the Cost field.
func (o *AIModelStats) SetCost(v int32) {
	o.Cost = &v
}

// GetIntelligence returns the Intelligence field value if set, zero value otherwise.
func (o *AIModelStats) GetIntelligence() int32 {
	if o == nil || IsNil(o.Intelligence) {
		var ret int32
		return ret
	}
	return *o.Intelligence
}

// GetIntelligenceOk returns a tuple with the Intelligence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AIModelStats) GetIntelligenceOk() (*int32, bool) {
	if o == nil || IsNil(o.Intelligence) {
		return nil, false
	}
	return o.Intelligence, true
}

// HasIntelligence returns a boolean if a field has been set.
func (o *AIModelStats) HasIntelligence() bool {
	if o != nil && !IsNil(o.Intelligence) {
		return true
	}

	return false
}

// SetIntelligence gets a reference to the given int32 and assigns it to the Intelligence field.
func (o *AIModelStats) SetIntelligence(v int32) {
	o.Intelligence = &v
}

// GetSpeed returns the Speed field value if set, zero value otherwise.
func (o *AIModelStats) GetSpeed() int32 {
	if o == nil || IsNil(o.Speed) {
		var ret int32
		return ret
	}
	return *o.Speed
}

// GetSpeedOk returns a tuple with the Speed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AIModelStats) GetSpeedOk() (*int32, bool) {
	if o == nil || IsNil(o.Speed) {
		return nil, false
	}
	return o.Speed, true
}

// HasSpeed returns a boolean if a field has been set.
func (o *AIModelStats) HasSpeed() bool {
	if o != nil && !IsNil(o.Speed) {
		return true
	}

	return false
}

// SetSpeed gets a reference to the given int32 and assigns it to the Speed field.
func (o *AIModelStats) SetSpeed(v int32) {
	o.Speed = &v
}

func (o AIModelStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AIModelStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cost) {
		toSerialize["cost"] = o.Cost
	}
	if !IsNil(o.Intelligence) {
		toSerialize["intelligence"] = o.Intelligence
	}
	if !IsNil(o.Speed) {
		toSerialize["speed"] = o.Speed
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AIModelStats) UnmarshalJSON(data []byte) (err error) {
	varAIModelStats := _AIModelStats{}

	err = json.Unmarshal(data, &varAIModelStats)

	if err != nil {
		return err
	}

	*o = AIModelStats(varAIModelStats)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cost")
		delete(additionalProperties, "intelligence")
		delete(additionalProperties, "speed")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAIModelStats struct {
	value *AIModelStats
	isSet bool
}

func (v NullableAIModelStats) Get() *AIModelStats {
	return v.value
}

func (v *NullableAIModelStats) Set(val *AIModelStats) {
	v.value = val
	v.isSet = true
}

func (v NullableAIModelStats) IsSet() bool {
	return v.isSet
}

func (v *NullableAIModelStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAIModelStats(val *AIModelStats) *NullableAIModelStats {
	return &NullableAIModelStats{value: val, isSet: true}
}

func (v NullableAIModelStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAIModelStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


