/*
vAudience AIgentChat API

chat and api server for AIgents

API version: 0.23.0
Contact: contact@vaudience.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aigentchat

import (
	"encoding/json"
	"fmt"
)

// checks if the Prompt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Prompt{}

// Prompt struct for Prompt
type Prompt struct {
	CreatedAt *int64 `json:"created_at,omitempty"`
	CurrentVersion *int32 `json:"current_version,omitempty"`
	DefaultAgentId *string `json:"default_agent_id,omitempty"`
	Description *string `json:"description,omitempty"`
	Id string `json:"id"`
	InternalId *string `json:"internal_id,omitempty"`
	OwnerId *string `json:"owner_id,omitempty"`
	OwnerOrganizationId *string `json:"owner_organization_id,omitempty"`
	Tags []string `json:"tags,omitempty"`
	ThumbnailUrl *string `json:"thumbnail_url,omitempty"`
	Title string `json:"title"`
	UpdatedAt *int64 `json:"updated_at,omitempty"`
	Versions []PromptVersion `json:"versions,omitempty"`
	Visibility *PromptVisibilityStates `json:"visibility,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Prompt Prompt

// NewPrompt instantiates a new Prompt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrompt(id string, title string) *Prompt {
	this := Prompt{}
	this.Id = id
	this.Title = title
	return &this
}

// NewPromptWithDefaults instantiates a new Prompt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptWithDefaults() *Prompt {
	this := Prompt{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Prompt) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Prompt) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *Prompt) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetCurrentVersion returns the CurrentVersion field value if set, zero value otherwise.
func (o *Prompt) GetCurrentVersion() int32 {
	if o == nil || IsNil(o.CurrentVersion) {
		var ret int32
		return ret
	}
	return *o.CurrentVersion
}

// GetCurrentVersionOk returns a tuple with the CurrentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetCurrentVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentVersion) {
		return nil, false
	}
	return o.CurrentVersion, true
}

// HasCurrentVersion returns a boolean if a field has been set.
func (o *Prompt) HasCurrentVersion() bool {
	if o != nil && !IsNil(o.CurrentVersion) {
		return true
	}

	return false
}

// SetCurrentVersion gets a reference to the given int32 and assigns it to the CurrentVersion field.
func (o *Prompt) SetCurrentVersion(v int32) {
	o.CurrentVersion = &v
}

// GetDefaultAgentId returns the DefaultAgentId field value if set, zero value otherwise.
func (o *Prompt) GetDefaultAgentId() string {
	if o == nil || IsNil(o.DefaultAgentId) {
		var ret string
		return ret
	}
	return *o.DefaultAgentId
}

// GetDefaultAgentIdOk returns a tuple with the DefaultAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetDefaultAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultAgentId) {
		return nil, false
	}
	return o.DefaultAgentId, true
}

// HasDefaultAgentId returns a boolean if a field has been set.
func (o *Prompt) HasDefaultAgentId() bool {
	if o != nil && !IsNil(o.DefaultAgentId) {
		return true
	}

	return false
}

// SetDefaultAgentId gets a reference to the given string and assigns it to the DefaultAgentId field.
func (o *Prompt) SetDefaultAgentId(v string) {
	o.DefaultAgentId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Prompt) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Prompt) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Prompt) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value
func (o *Prompt) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Prompt) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Prompt) SetId(v string) {
	o.Id = v
}

// GetInternalId returns the InternalId field value if set, zero value otherwise.
func (o *Prompt) GetInternalId() string {
	if o == nil || IsNil(o.InternalId) {
		var ret string
		return ret
	}
	return *o.InternalId
}

// GetInternalIdOk returns a tuple with the InternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetInternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.InternalId) {
		return nil, false
	}
	return o.InternalId, true
}

// HasInternalId returns a boolean if a field has been set.
func (o *Prompt) HasInternalId() bool {
	if o != nil && !IsNil(o.InternalId) {
		return true
	}

	return false
}

// SetInternalId gets a reference to the given string and assigns it to the InternalId field.
func (o *Prompt) SetInternalId(v string) {
	o.InternalId = &v
}

// GetOwnerId returns the OwnerId field value if set, zero value otherwise.
func (o *Prompt) GetOwnerId() string {
	if o == nil || IsNil(o.OwnerId) {
		var ret string
		return ret
	}
	return *o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetOwnerIdOk() (*string, bool) {
	if o == nil || IsNil(o.OwnerId) {
		return nil, false
	}
	return o.OwnerId, true
}

// HasOwnerId returns a boolean if a field has been set.
func (o *Prompt) HasOwnerId() bool {
	if o != nil && !IsNil(o.OwnerId) {
		return true
	}

	return false
}

// SetOwnerId gets a reference to the given string and assigns it to the OwnerId field.
func (o *Prompt) SetOwnerId(v string) {
	o.OwnerId = &v
}

// GetOwnerOrganizationId returns the OwnerOrganizationId field value if set, zero value otherwise.
func (o *Prompt) GetOwnerOrganizationId() string {
	if o == nil || IsNil(o.OwnerOrganizationId) {
		var ret string
		return ret
	}
	return *o.OwnerOrganizationId
}

// GetOwnerOrganizationIdOk returns a tuple with the OwnerOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetOwnerOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OwnerOrganizationId) {
		return nil, false
	}
	return o.OwnerOrganizationId, true
}

// HasOwnerOrganizationId returns a boolean if a field has been set.
func (o *Prompt) HasOwnerOrganizationId() bool {
	if o != nil && !IsNil(o.OwnerOrganizationId) {
		return true
	}

	return false
}

// SetOwnerOrganizationId gets a reference to the given string and assigns it to the OwnerOrganizationId field.
func (o *Prompt) SetOwnerOrganizationId(v string) {
	o.OwnerOrganizationId = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Prompt) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Prompt) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Prompt) SetTags(v []string) {
	o.Tags = v
}

// GetThumbnailUrl returns the ThumbnailUrl field value if set, zero value otherwise.
func (o *Prompt) GetThumbnailUrl() string {
	if o == nil || IsNil(o.ThumbnailUrl) {
		var ret string
		return ret
	}
	return *o.ThumbnailUrl
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetThumbnailUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ThumbnailUrl) {
		return nil, false
	}
	return o.ThumbnailUrl, true
}

// HasThumbnailUrl returns a boolean if a field has been set.
func (o *Prompt) HasThumbnailUrl() bool {
	if o != nil && !IsNil(o.ThumbnailUrl) {
		return true
	}

	return false
}

// SetThumbnailUrl gets a reference to the given string and assigns it to the ThumbnailUrl field.
func (o *Prompt) SetThumbnailUrl(v string) {
	o.ThumbnailUrl = &v
}

// GetTitle returns the Title field value
func (o *Prompt) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *Prompt) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *Prompt) SetTitle(v string) {
	o.Title = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Prompt) GetUpdatedAt() int64 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Prompt) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *Prompt) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

// GetVersions returns the Versions field value if set, zero value otherwise.
func (o *Prompt) GetVersions() []PromptVersion {
	if o == nil || IsNil(o.Versions) {
		var ret []PromptVersion
		return ret
	}
	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetVersionsOk() ([]PromptVersion, bool) {
	if o == nil || IsNil(o.Versions) {
		return nil, false
	}
	return o.Versions, true
}

// HasVersions returns a boolean if a field has been set.
func (o *Prompt) HasVersions() bool {
	if o != nil && !IsNil(o.Versions) {
		return true
	}

	return false
}

// SetVersions gets a reference to the given []PromptVersion and assigns it to the Versions field.
func (o *Prompt) SetVersions(v []PromptVersion) {
	o.Versions = v
}

// GetVisibility returns the Visibility field value if set, zero value otherwise.
func (o *Prompt) GetVisibility() PromptVisibilityStates {
	if o == nil || IsNil(o.Visibility) {
		var ret PromptVisibilityStates
		return ret
	}
	return *o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Prompt) GetVisibilityOk() (*PromptVisibilityStates, bool) {
	if o == nil || IsNil(o.Visibility) {
		return nil, false
	}
	return o.Visibility, true
}

// HasVisibility returns a boolean if a field has been set.
func (o *Prompt) HasVisibility() bool {
	if o != nil && !IsNil(o.Visibility) {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given PromptVisibilityStates and assigns it to the Visibility field.
func (o *Prompt) SetVisibility(v PromptVisibilityStates) {
	o.Visibility = &v
}

func (o Prompt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Prompt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CurrentVersion) {
		toSerialize["current_version"] = o.CurrentVersion
	}
	if !IsNil(o.DefaultAgentId) {
		toSerialize["default_agent_id"] = o.DefaultAgentId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.InternalId) {
		toSerialize["internal_id"] = o.InternalId
	}
	if !IsNil(o.OwnerId) {
		toSerialize["owner_id"] = o.OwnerId
	}
	if !IsNil(o.OwnerOrganizationId) {
		toSerialize["owner_organization_id"] = o.OwnerOrganizationId
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.ThumbnailUrl) {
		toSerialize["thumbnail_url"] = o.ThumbnailUrl
	}
	toSerialize["title"] = o.Title
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Versions) {
		toSerialize["versions"] = o.Versions
	}
	if !IsNil(o.Visibility) {
		toSerialize["visibility"] = o.Visibility
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Prompt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrompt := _Prompt{}

	err = json.Unmarshal(data, &varPrompt)

	if err != nil {
		return err
	}

	*o = Prompt(varPrompt)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "current_version")
		delete(additionalProperties, "default_agent_id")
		delete(additionalProperties, "description")
		delete(additionalProperties, "id")
		delete(additionalProperties, "internal_id")
		delete(additionalProperties, "owner_id")
		delete(additionalProperties, "owner_organization_id")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "thumbnail_url")
		delete(additionalProperties, "title")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "versions")
		delete(additionalProperties, "visibility")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrompt struct {
	value *Prompt
	isSet bool
}

func (v NullablePrompt) Get() *Prompt {
	return v.value
}

func (v *NullablePrompt) Set(val *Prompt) {
	v.value = val
	v.isSet = true
}

func (v NullablePrompt) IsSet() bool {
	return v.isSet
}

func (v *NullablePrompt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrompt(val *Prompt) *NullablePrompt {
	return &NullablePrompt{value: val, isSet: true}
}

func (v NullablePrompt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrompt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


