/*
vAudience AIgentChat API

chat and api server for AIgents

API version: 0.15.12
Contact: contact@vaudience.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aigentchat

import (
	"encoding/json"
	"fmt"
)

// AgentPromptVisibilityStates the model 'AgentPromptVisibilityStates'
type AgentPromptVisibilityStates string

// List of AgentPromptVisibilityStates
const (
	AgentPromptVisibilityPrivate AgentPromptVisibilityStates = "private"
	AgentPromptVisibilityOrganization AgentPromptVisibilityStates = "org"
	AgentPromptVisibilityPublic AgentPromptVisibilityStates = "public"
	AgentPromptVisibilityCurated AgentPromptVisibilityStates = "curated"
)

// All allowed values of AgentPromptVisibilityStates enum
var AllowedAgentPromptVisibilityStatesEnumValues = []AgentPromptVisibilityStates{
	"private",
	"org",
	"public",
	"curated",
}

func (v *AgentPromptVisibilityStates) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AgentPromptVisibilityStates(value)
	for _, existing := range AllowedAgentPromptVisibilityStatesEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AgentPromptVisibilityStates", value)
}

// NewAgentPromptVisibilityStatesFromValue returns a pointer to a valid AgentPromptVisibilityStates
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAgentPromptVisibilityStatesFromValue(v string) (*AgentPromptVisibilityStates, error) {
	ev := AgentPromptVisibilityStates(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AgentPromptVisibilityStates: valid values are %v", v, AllowedAgentPromptVisibilityStatesEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AgentPromptVisibilityStates) IsValid() bool {
	for _, existing := range AllowedAgentPromptVisibilityStatesEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AgentPromptVisibilityStates value
func (v AgentPromptVisibilityStates) Ptr() *AgentPromptVisibilityStates {
	return &v
}

type NullableAgentPromptVisibilityStates struct {
	value *AgentPromptVisibilityStates
	isSet bool
}

func (v NullableAgentPromptVisibilityStates) Get() *AgentPromptVisibilityStates {
	return v.value
}

func (v *NullableAgentPromptVisibilityStates) Set(val *AgentPromptVisibilityStates) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentPromptVisibilityStates) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentPromptVisibilityStates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentPromptVisibilityStates(val *AgentPromptVisibilityStates) *NullableAgentPromptVisibilityStates {
	return &NullableAgentPromptVisibilityStates{value: val, isSet: true}
}

func (v NullableAgentPromptVisibilityStates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentPromptVisibilityStates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

