/*
vAudience AI File Manager API

API for the vAudience AI File Manager

API version: 0.22.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package filemanager

import (
	"encoding/json"
)

// checks if the CollectionListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionListResponse{}

// CollectionListResponse struct for CollectionListResponse
type CollectionListResponse struct {
	Collections []CollectionResponse `json:"collections,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
	Summary *CollectionSummary `json:"summary,omitempty"`
	Total *int64 `json:"total,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CollectionListResponse CollectionListResponse

// NewCollectionListResponse instantiates a new CollectionListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionListResponse() *CollectionListResponse {
	this := CollectionListResponse{}
	return &this
}

// NewCollectionListResponseWithDefaults instantiates a new CollectionListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionListResponseWithDefaults() *CollectionListResponse {
	this := CollectionListResponse{}
	return &this
}

// GetCollections returns the Collections field value if set, zero value otherwise.
func (o *CollectionListResponse) GetCollections() []CollectionResponse {
	if o == nil || IsNil(o.Collections) {
		var ret []CollectionResponse
		return ret
	}
	return o.Collections
}

// GetCollectionsOk returns a tuple with the Collections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionListResponse) GetCollectionsOk() ([]CollectionResponse, bool) {
	if o == nil || IsNil(o.Collections) {
		return nil, false
	}
	return o.Collections, true
}

// HasCollections returns a boolean if a field has been set.
func (o *CollectionListResponse) HasCollections() bool {
	if o != nil && !IsNil(o.Collections) {
		return true
	}

	return false
}

// SetCollections gets a reference to the given []CollectionResponse and assigns it to the Collections field.
func (o *CollectionListResponse) SetCollections(v []CollectionResponse) {
	o.Collections = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *CollectionListResponse) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionListResponse) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *CollectionListResponse) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *CollectionListResponse) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *CollectionListResponse) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *CollectionListResponse) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *CollectionListResponse) SetOffset(v int32) {
	o.Offset = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *CollectionListResponse) GetSummary() CollectionSummary {
	if o == nil || IsNil(o.Summary) {
		var ret CollectionSummary
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionListResponse) GetSummaryOk() (*CollectionSummary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *CollectionListResponse) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given CollectionSummary and assigns it to the Summary field.
func (o *CollectionListResponse) SetSummary(v CollectionSummary) {
	o.Summary = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *CollectionListResponse) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionListResponse) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *CollectionListResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *CollectionListResponse) SetTotal(v int64) {
	o.Total = &v
}

func (o CollectionListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Collections) {
		toSerialize["collections"] = o.Collections
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CollectionListResponse) UnmarshalJSON(data []byte) (err error) {
	varCollectionListResponse := _CollectionListResponse{}

	err = json.Unmarshal(data, &varCollectionListResponse)

	if err != nil {
		return err
	}

	*o = CollectionListResponse(varCollectionListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "collections")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "offset")
		delete(additionalProperties, "summary")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCollectionListResponse struct {
	value *CollectionListResponse
	isSet bool
}

func (v NullableCollectionListResponse) Get() *CollectionListResponse {
	return v.value
}

func (v *NullableCollectionListResponse) Set(val *CollectionListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionListResponse(val *CollectionListResponse) *NullableCollectionListResponse {
	return &NullableCollectionListResponse{value: val, isSet: true}
}

func (v NullableCollectionListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


