/*
vAudience AI File Manager API

Testing CollectionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package filemanager

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vaudience/nexus-go-clients/filemanager"
)

func Test_filemanager_CollectionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CollectionsAPIService CreateCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		resp, httpRes, err := apiClient.CollectionsAPI.CreateCollection(context.Background(), orgId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService DeleteCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var collectionId string

		httpRes, err := apiClient.CollectionsAPI.DeleteCollection(context.Background(), orgId, collectionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService GetCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var collectionId string

		resp, httpRes, err := apiClient.CollectionsAPI.GetCollection(context.Background(), orgId, collectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService GetCollectionFile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var collectionId string
		var fileId string

		resp, httpRes, err := apiClient.CollectionsAPI.GetCollectionFile(context.Background(), orgId, collectionId, fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService GetCollectionSettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		resp, httpRes, err := apiClient.CollectionsAPI.GetCollectionSettings(context.Background(), orgId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService ListCollectionFiles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var collectionId string

		resp, httpRes, err := apiClient.CollectionsAPI.ListCollectionFiles(context.Background(), orgId, collectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService ListMyCollections", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		resp, httpRes, err := apiClient.CollectionsAPI.ListMyCollections(context.Background(), orgId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService RetryCollectionFile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var collectionId string
		var fileId string

		httpRes, err := apiClient.CollectionsAPI.RetryCollectionFile(context.Background(), orgId, collectionId, fileId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CollectionsAPIService UpdateCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var collectionId string

		resp, httpRes, err := apiClient.CollectionsAPI.UpdateCollection(context.Background(), orgId, collectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
